import './globals.css'
import { Nunito } from 'next/font/google'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Components/Navbar/Navbar'
import ClientOnly from './Components/Navbar/ClientOnly'

import RegisterModal from './Components/Modals/RegisterModal'
import ToasterProvider from './Providers/ToasterProvider'
import LoginModal from './Components/Modals/LoginModal'
import getCurrentUser from './action/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '1',
  description: 'Generated by create next app',
}
const font =  Nunito ( {
  subsets: ["latin"], 
})
export default async  function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser  = await getCurrentUser()

  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider/>
          <RegisterModal/>
          <LoginModal/>
        <Navbar currentUser={currentUser}/>
        </ClientOnly>
        {children}</body>
    </html>
  )
}
